# Generated by Django 4.2.4 on 2023-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ingrese el título de la tarea.', max_length=200)),
                ('description', models.TextField(help_text='Ingrese la descripción de la tarea.')),
            ],
        ),
    ]
